# Generated by Django 5.2.2 on 2025-09-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_bus_assigned_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='assigned_conductor',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='bus',
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(related_name='routes', through='ticketing.RouteStop', to='ticketing.stop'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
