# Generated by Django 5.2.2 on 2025-09-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_remove_bus_assigned_conductor_remove_ticket_bus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='number',
        ),
        migrations.AddField(
            model_name='bus',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='stop',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
