# Generated by Django 5.2.2 on 2025-09-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_remove_bus_is_active_remove_bus_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'stop')},
        ),
        migrations.RemoveField(
            model_name='bus',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='current_speed',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='route',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(db_index=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='destination_stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_destination', to='ticketing.stop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='origin_stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_origin', to='ticketing.stop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busss', to='ticketing.route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.route'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'order'), ('route', 'stop')},
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('current_speed', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='ticketing.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='ticketing.route')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='journey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticketing.journey'),
            preserve_default=False,
        ),
    ]
