# Generated by Django 5.2.2 on 2025-09-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_bus_current_latitude_bus_current_longitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusLocation',
        ),
    ]
